execute pathogen#infect()
syntax on
filetype plugin indent on

set background=dark
let g:base16colorspace=256
let g:theme_name = 'base16-google-dark'
let g:airline_powerline_fonts = 1

"hybrid line numbers, normal numbers in insert mode
:set number relativenumber
:augroup numbertoggle
:  autocmd!
:  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
:  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
:augroup END

"Uses instatn searching, not waiting for enter
set incsearch

"Smart search
set ignorecase
set smartcase
