#!/bin/bash
if [ "$1" == "low" ]
then
 light -U 5
 TEXT=$(light -G)
elif [ "$1" == "high" ]
then
 light -A 5
 TEXT=$(light -G)
else
 echo "Usage brightness [low | high]\n"
fi

 ICON="/usr/share/icons/HighContrast/16x16/status/display-brightness.png"
ID=$(cat /home/nikhil/.i3/.dunst_brightness)
if [ $ID -gt "0" ]
then
 dunstify -p -r $ID -i $ICON "Brightness: $TEXT%" >/home/nikhil/.i3/.dunst_brightness
else
 dunstify -p -i $ICON "Brightness: $TEXT%" >/home/nikhil/.i3/.dunst_brightness
fi
